# disable deep sleep
CONFIG_ZMK_SLEEP=n

# increase the transmit power of the ble radio
# this also increases the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# enable experimental bluetooth connection settings
# currently only disables 2m phy support
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# eager debouncing
# see here: https://zmk.dev/docs/features/debouncing#eager-debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
